avance2/belledluxe/belleluxe/belleluxe/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('adm/', include("core.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

avance2/belledluxe/belleluxe/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views


app_name="core"
urlpatterns=[
    path('', views.adm.as_view(), name="adm"),

    path('camping/', views.Campaign.as_view(), name="campaign"),
    path('detail/camping/<int:pk>/', views.DetailCampaign.as_view(), name='detail_campaign'),
    path('update/camping/<int:pk>/', views.UpdateCampaign.as_view(), name='update_campaign'),
    path('delete/camping/<int:pk>/', views.DeleteCampaign.as_view(), name='delete_campaign'),
    path('new/camping/', views.NewCampaign.as_view(), name='Newcampaign'),

    path('list/gender/', views.list_gender.as_view(), name="gender"),
    path('detail/gender/<int:pk>/', views.DetailGender.as_view(), name='detail_gender'),
    path('update/gender/<int:pk>/', views.UpdateGender.as_view(), name='update_gender'),
    path('delete/gender/<int:pk>/', views.DeleteGender.as_view(), name='delete_gender'),
    path('new/gender/', views.NewGender.as_view(), name='Newgender'),

    path('list/category/', views.list_category.as_view(), name="category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name='update_category'),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),
    path('new/category/', views.NewCategory.as_view(), name='Newcategory'),

    path('list/payment/', views.list_payment.as_view(), name="payment"),
    path('detail/payment/<int:pk>/', views.DetailPayment.as_view(), name='detail_payment'),
    path('update/payment/<int:pk>/', views.UpdatePayment.as_view(), name='update_payment'),
    path('delete/payment/<int:pk>/', views.DeletePayment.as_view(), name='delete_payment'),
    path('new/payment/', views.NewPayment.as_view(), name='Newpayment'),

    path('product/', views.Product.as_view(), name="product"),
    path('recover/product/<int:pk>/', views.RecoverProduct.as_view(), name='recover_product'),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name='update_product'),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name='delete_product'),
    path('new/product/', views.NewProduct.as_view(), name='new_product'),
   
]

avance2/belledluxe/belleluxe/home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

# NOOO 😨 eso truena el django 😔
#oh perdon ya no le muevo, perdoname compañero unu. 
#adios
app_name="home"
urlpatterns=[
    path('', views.inicio.as_view(), name="inicio"),
    path('nosotros/', views.nosotros.as_view(), name="nosotros"),
    path('blog/', views.blog.as_view(), name="blog"),
    path('servicios/', views.servicios.as_view(), name="servicios"),
    path('politicas/', views.politicas.as_view(), name="politicas"),
    path('carrito/', views.carrito.as_view(), name="carrito"),
]

avance2/belledluxe/belleluxe/home/models.py
from django.db import models

# Create your models here.

avance2/belledluxe/belleluxe/home/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.
class inicio(generic.View):
    tamplate_name="home/inicio.html"
    context={} 
    def get(self, request):
        return render(request, self.tamplate_name, self.context)
    
class nosotros(generic.View):
    tamplate_name="home/nosotros.html"
    context={}
    def get(self, request):
        return render(request, self.tamplate_name, self.context)
    
class blog(generic.View):
    tamplate_name="home/blog.html"
    context={}
    def get(self, request):
        return render(request, self.tamplate_name, self.context)
    
class servicios(generic.View):
    tamplate_name="home/servicios.html"
    context={}
    def get(self, request):
        return render(request, self.tamplate_name, self.context)

class politicas(generic.View):
    tamplate_name="home/politicas.html"
    context={}
    def get(self, request):
        return render(request, self.tamplate_name, self.context)
    
class carrito(generic.View):
    tamplate_name="home/carrito.html"
    context={}
    def get(self, request):
        return render(request, self.tamplate_name, self.context)

avance2/belledluxe/belleluxe/templates/home/blog.html
{% extends 'base/base.html' %}

{% block title %}Blog{% endblock title %}


{% block content %}
<style>
    .blanco{
      color: white;
    }
  </style>
  <title> Blog </title>

    <h1 class="blanco">BLOG</h1>
    <br>
    <br>
    <br>
    <hr>
    <p class="blanco"> 
       En BELLE D' LUXE su filosofia de empresa se redefine al concepto del lujo. El lujo no se trata de adquirir
       prendas de alto valor, sino de la interpretacion hacia la comodidad y la confianza en cada pieza que ofrecemos. 
       BUscamos crear una belleza incondicional unica en cada persona, haciendo que nuestros clientes, se sientan verdaderamente
       especiales
    </p>
    <br>
    <p class="blanco">
        Nuestra mision es innovar en la moda de una manera sostenible, sin causar danos al entorno natural.
        Nos esforzamos por proporcionar prendas que no solo se ven bien, sino que tambien generen una sensacion de comodidad, 
        seguridad y confianza en quienes las usan. Creemos que la verdadera belleza de lujo es aquella que se siente desde adentro.
    </p>
    <br>
    <p class="blanco">
        EN cuanto, nuestra vision, aspiramos a ser un referente a la industria, desafiando la diversidad y promoverlo la igualdad.
        Nos esforzamos por disenar y ofrecer productos innovadores, novedosos y sofisticados, agregando un toque de glamour a cada prenda.
        Nuestro objetivo es no solo vestir a nuestros clientesm tambien potenciar su confianza y personalidad
        permitiendoles destacar en su estilo unico. En BELLE D' LUXE se compromete con la excelencia y la autenticidad en la moda del lujo.
    </p>
    
    {% endblock content %}

avance2/belledluxe/belleluxe/templates/home/carrito.html
{% extends 'base/base.html' %}

{% block title %} carrito {% endblock title %}


{% block content %}
<style>
  .blanco{
    color: white;
  }
</style>
<title> Carrito </title>

                    
                <!-- QUI IRAN LAS COLUMNAS -->
                
                <div class="container mt-5">
                    <div class="row">
                      <div class="col-sm-4">
                        <center> <h6 class="blanco" style="color:white;">Photo of me:</h6></center>
                        <div class="container py-4" style="width:200px"> 
                         <img style="width:200px" src="imagen vacia.avif" alt="">
                        </div>
                        <div class="fakeimg" style="color:white;">FACHIU</div>
                        <p class="blanco">Lorem ipsum dolor sit ame.</p>
                        <ul class="nav nav-pills flex-column">
                          <li class="nav-item">
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#" style="color:white;">Disabled</a>
                          </li>
                        </ul>
                        <hr class="d-sm-none">
                      </div>
                      <div class="col-sm-4">
                        <br>
                        
                        <br>
                        <h5 class="blanco">Nombre del producto</h5>
                        <div>
                         <p class="blanco"> Descripcion de la prenda que se va a comprar </p>   
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <br>
                        <br>

                        <center><INPUT TYPE="NUMBER"  MIN="0" MAX="100" STEP="1" VALUE="6" SIZE="6" pattern="[0-9]*"></center>
                      </div>
                    </div>
                  </div>
                  


            
             
             

{% endblock content %}

avance2/belledluxe/belleluxe/templates/home/inicio.html
{% extends 'base/base.html' %}

{% block title %} inicio {% endblock title %}


{% block content %}
<title> Inicio </title>
    <!-- fin de la barra de navegacion -->
    <!-- inicio del cuerpo -->

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    {% endblock content %}


    
    <div class="position-absolute top-100 start-50 translate-middle"><p> </p></div>
          <!-- Grid container -->
          <div class="container pt-4 text-center">



            <div class="text-center text-white p-3">
                <ul>
                    <a class="text-white" href="{% url 'home:nosotros' %}">Sobre belle d'luxe</a>
                    <li class="list-inline-item"></li>
                    <li class="list-inline-item"></li>
                    <a class="text-white" href="{% url 'home:blog' %}">Nuestro blog</a>
                    <li class="list-inline-item"></li>
                    <li class="list-inline-item"></li>
                    <a class="text-white" href="{% url 'home:servicios' %}">Servicios</a>

                  </ul>              
            </div>


  

            <!-- Section: Social media -->
            <section class="mb-4">
              <!-- Facebook -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="https://www.facebook.com/belleedeluxe"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="bi bi-facebook" style="font-size: 100%; color: white;" ></i></a>
        
              <!-- Google -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="https://www.google.com/search?q=belle+de+luxe+tijuana&sca_esv=573670241&biw=1920&bih=937&tbm=lcl&ei=tY0sZb_JKd_UkPIP4OuFqAM&ved=0ahUKEwj_98WqsfmBAxVfKkQIHeB1ATUQ4dUDCAk&uact=5&oq=belle+de+luxe+tijuana&gs_lp=Eg1nd3Mtd2l6LWxvY2FsIhViZWxsZSBkZSBsdXhlIHRpanVhbmEyChAhGKABGMMEGApI_hBQkw1Ykw1wAHgAkAEAmAGTAaAB2gKqAQMxLjK4AQPIAQD4AQHCAgUQABiiBMICCBAAGIkFGKIEiAYB&sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[32.52364412063617,-116.93859226079246],[32.49498109755391,-117.00296527714988]]"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="bi bi-google" style="font-size: 100%; color: white;"></i
              ></a>
        
              <!-- Instagram -->
              <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="https://www.instagram.com/belleedeluxe/"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="bi bi-instagram" style="font-size: 100%; color: white;" ></i></a>


                <!-- Tiktok -->
                <a
                class="btn btn-link btn-floating btn-lg text-dark m-1"
                href="https://www.tiktok.com/@belleedeluxe"
                role="button"
                data-mdb-ripple-color="dark"
                ><i class="bi bi-tiktok" style="font-size: 100%; color: white;" ></i></a>
            </section>
            <!-- Section: Social media -->

            

        </div>
          <!-- Grid container -->
        
          <!-- Copyright -->
          <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            <ul class="list-inline">
                <li class="list-inline-item">            @belledeluxe Baja California Norte, México             </li>
                <li class="list-inline-item"></li>
                <a class="text-white" href="{% url 'home:politicas' %}">politica de privacidad y cookies | condiciones de venta</a>
              </ul>              
          </div>
          <!-- Copyright -->
        


          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>    
</body>
</html>

avance2/belledluxe/belleluxe/templates/home/nosotros.html
{% extends 'base/base.html' %}

{% block title %}Nosotros{% endblock title %}



{% block content %}


<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sobre nosotros</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

 <link rel="stylesheet" href="css-exclusivo-pro-admi-vip/westyle.css">
<nav class="nav">
  <a class="nav-link active" aria-current="page" href="{% url 'home:inicio' %}">BELLE D' LUXE</a>
</nav>
 ¿Vas a poner el mismo encavesado en muchas paguinas? -->
<!-- Si es el caso usa herencia -->
<!-- poner la base dices?-->
<!-- si -->
<!-- ok lo intentaré jeje-->
<!-- Pero si estaria bien o no???? -->
<!-- lo cuparemos apra 3 q 4 paginas esa barrita nomas jé -->
<!-- Siiii m abisas jeje ke me duermo o me baño kjwdnkw aino ke chistoso esto-->
<!-- ba te recomendaria descansar un rato -->
<!-- i despetar más tarde i seguir? asi le ases omg tip julio  -->
<!-- yo no duermo 😎 -->
<!-- porke deberia, luego se le hara pesado compañero, me paso i ahora-->
<!-- no puedo dormir tarde jeje, me iré a bañar en lo ke se ase las carptas vaaaa?-->
<!-- va recuerda que tenemos tarea del profe ray y fortigod -->
<!-- keeeeeeeeeee, nooo par amañana es la investigacion, me voi a  -->
<!-- i fortino? kual de fortino, no puede ser aaaaaaaaaaaaaaaa -->
<!-- es anotar( lo que no le dio tiempo a explicar) lo que supuestamente iba subir a teams (nunca subio la parte de la presentacion) -->
<!-- ademas para crear comentarios es con ctrl + k + c -->

<!-- aaa ya se cual, y la de rai, es para mañana?
lo de rebeca ya lo hicite?
ii se me olvido otra kosa ke iba a desir jeje 😂-->
<!-- lo de la profe reveca se encarga sebas si si si -->
<!-- con repecto a lo del profe ray segun yo si es para mañana,
  pero dudo que la revise asi como las investigacines del primer parcial -->
<!-- ya me acorde-->
<!--julioanimator SWNJDKWNJD-->
<!-- no te burles 😡 esta bien epico mi nombre  -->
<!--de que era la tareaaaaa, compañero-->
<!--siii solo ke es mui foni tu creatividad, mui unico KJDWNDW-->
<!--como es que pones emojiiiis, tu teclado tiene ?-->
<!-- la tarea es de herencia de plantillas django -->
<!-- es que estoy en windows y preciono win + . -->
<!--okeiiiii, ya estubo, esperame tantito, ahora si me meto a bañar i chambeo-->
<!--no borres los comentarios, bueno el de la tarea, ahorita lo voy a checar bnnnnn, ahorita que venga jeje-->
<!--oneminute-->

<!-- va -->
<!--compañero, la tarea es ingles ok-->
<!-- eso si nose -->
<!--es afrimacion jeje, kari le question-->
<!-- no puede ser que flojeraaaaaaaa -->
<!-- daaah, solo traduce -->
<!-- pero es a mano? -->
<!--noooooo, como vas hacer el formato IEEE, a mano-->
<!-- usas las manos para escribir en el teclado daaah -->
<!--aiiiiii ke dificil refutar eso -->
<!-- es que es la verdad 😎 -->
<!-- tene logica-->
<!--and shi gun meik your ais roll-->
<!-- Mejor hay que ver tiktoks en ves de hacer el proyecto -->
<!--siiiiiiii, pasa tistoks uwu i no dormimos por ver tistoks-->
<!-- no tengo tiktok en windows 🥲 -->
<!--q tite lloro-->
<!-- 😭😭😭😭😭😭😭 -->
<!-- 😭😭😭😭😭😭😭😭😭😭😭😭😭😭 -->
<!--komo le psusite de titilo a la tarea jeje-->
<!-- no la he hecho, yo soy mas de hacerla en la noche 😎 -->
<!-- me robasteee mis corchetes de comentarios-->
<!-- pero compañero ya es noche, daaaah -->
<!-- jajaja  -->
<!-- te ries, nom voi a pelear, respiro inhalo -->
<!-- no pelies 🤝 -->
<!-- porciento ya hice lo del base nadamas que no que diseño requiera-->
<!-- se lo puese al de politicas para probarlo -->
<!-- es que, hay paginas que tenen el mismo diseño, pero hay otras que no pero tambb repite-->
<!-- cómo lo miro -->

  <style>
    .blanco{
      color: white;
    }
  </style>
  <title> Nosotros </title>

    <br>


    <br>


    <h1 class="blanco">Acerca de nosotros</h1>
    <br>

    <hr>

<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <p class="blanco"> Nosotros en BELLE D- LUXE somos una marca de moda de lujo para hombres y mujeres
        que se origino dentro de la empresa de Rubis Collection fundada por el equipo
        comprometido: Xahil Alvarez, Julio Barron Quintana, Karime Pulido e Itzel Ruiz Pacheco.
        Nuestros valores fundamentales incluten el respeto, la responsabilidad, la igualdad, el compromiso
        la calidad, empatia y la libertad. Respetamos a cada indivuduo en todos los aspectos, asumimos
        la responsabilidad en todas nuestras acciones promovemos la igualdad y la diversidad. Nos comprometemos
        a ofrecer lo mejor en un ambiente positivo, valoramos la calidad y empatia en nuestro servicio al cliente
        y permitimos la libertad creativa de nuestro equipo, logrando nuestros objetivos profesionales.
             </p>
    </div>
    <div class="col-sm-4">
      <h3 class="blanco">imagen3</h3>

    </div>
  </div>

<footer>
<div class="footer mt-8 p-4">
  <p class="blanco">Footer</p>
</div>
</div>
</footer>
    {% endblock content %}

avance2/belledluxe/belleluxe/templates/home/politicas.html
{% extends 'base/base.html' %}

{% block title %}Políticas{% endblock title %}


{% block content %}
<!-- Entra a la pagina y te entra a ese apartado ola -->
<!-- ola-->
<!-- ya biiiii, creo que está bien, solo que se le pude cambiar el fondo
indidualmente, o siempre será verde, porkee algunos tiene blanco como fondo
en el wife-->
<!-- va -->
<!-- que iria en imagen 3 -->

<!-- un imagen lateral daaah kjwdndjkw-->

<!-- No puedo con esa logica tan logica  -->
<!-- es muy logica vdd-->
<!-- bueno, como te decia, mmmm-->
<!-- pondre la herencia en las demás i ya vemos ke disen luego ajajaja-->
<!-- pa tener algo-->
<!-- juliooo es pregunta jajajajajaja -->
<!-- Creo que estaria bien todo verde, pero hay que preguntarle al equipo que opina -->
<!-- Igual lel profe ray dijo que nunca quedan iguales los mukups al diseño final -->
<!-- siiii, bueno lo pondre verde por ahora, ya que le comentemos en ekipo vemos-->
<!-- por el momento berde jeje-->
<!-- pero elimnaste mi css -->
<!-- lo movi para que lo detectara el html -->

<!-- va, por el momento tendre que hacer la tarea del profe ray -->
<!-- si necesitas ayuda en algo me avisas por whatsap o por correo postal 


va va nos vemos

correpostal ya cerraron, correo de mejiko jeejej fedex no a cerrado o eso creo
aaaaaaaaaaa ping desde el cdmd
ovbio que desde cmd
 yo de grande trabajare en fedex, estemmmm ya tas grande jeje oye 😡😡 yo esto chavo 

amm si compañero, esta bien, pero no se enoje :(

serbicio de 24 hrs fedex si-->
<style>
    .blanco{
      color: white;
    }
  </style>
  <title> Politicas </title>

<p class="blanco">
Aviso Legal:

Bienvenido al sitio web de Belle D'Luxe. Por favor, lea atentamente los siguientes términos y condiciones antes de usar nuestro sitio web. Al acceder y utilizar este sitio, acepta cumplir y estar sujeto a estos términos y condiciones.

Política de Privacidad:

Esta Política de Privacidad describe cómo Belle D'Luxe recopila, utiliza y protege la información que usted nos proporciona cuando utiliza nuestro sitio web. Respetamos su privacidad y nos comprometemos a proteger su información personal. Lea esta política de privacidad detenidamente para comprender cómo tratamos sus datos.

    Recopilación de Información: Recopilamos información personal que usted nos proporciona voluntariamente, como su nombre, dirección de correo electrónico, dirección de envío, número de teléfono, etc., al realizar una compra o registrarse en nuestro sitio web.

    Uso de la Información: Utilizamos su información para procesar pedidos, proporcionar asistencia al cliente, mejorar nuestros productos y servicios, y enviarle información promocional, si ha dado su consentimiento.

    Protección de Datos: Sus datos personales se almacenan de forma segura y protegida. No vendemos ni compartimos su información con terceros sin su consentimiento.

    Política de Cookies: Utilizamos cookies para mejorar su experiencia en nuestro sitio web. Puede configurar sus preferencias de cookies en su navegador.

    Derechos del Usuario: Usted tiene derecho a acceder, corregir, eliminar o limitar el uso de sus datos personales. Puede ejercer estos derechos poniéndose en contacto con nosotros.

Política de Cookies:

Nuestro sitio web utiliza cookies para mejorar la experiencia del usuario. Las cookies son pequeños archivos de texto que se almacenan en su dispositivo cuando visita nuestro sitio. Estas cookies nos ayudan a analizar el tráfico del sitio, personalizar el contenido y ofrecer anuncios dirigidos.

    Tipos de Cookies: Utilizamos cookies de sesión y cookies persistentes, así como cookies de terceros para analítica y publicidad.

    Gestión de Cookies: Puede configurar sus preferencias de cookies en su navegador. Tenga en cuenta que la desactivación de ciertas cookies puede afectar su experiencia en nuestro sitio web.

Condiciones Generales de Venta:

Estas condiciones generales se aplican a todas las compras realizadas en Belle D'Luxe. Al realizar un pedido en nuestro sitio, acepta estas condiciones.

    Productos y Precios: Nos esforzamos por ofrecer productos de alta calidad a precios competitivos. Los precios y la disponibilidad están sujetos a cambios sin previo aviso.

    Envío: El envío se realizará a la dirección que nos proporcione. Los tiempos de entrega pueden variar.

    Devoluciones y Reembolsos: Aceptamos devoluciones dentro de los 30 días posteriores a la recepción del producto. Para más detalles, consulte nuestra política de devoluciones en nuestro sitio web.

    Pagos: Aceptamos pagos en línea a través de métodos seguros. Su información de pago se cifra y se mantiene de forma segura.

    Contacto: Si tiene alguna pregunta o necesita asistencia, no dude en ponerse en contacto con nuestro equipo de atención al cliente.
</p>

{% endblock content %}