ProyectoExpo/belleluxe/belleluxe/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('adm/', include("core.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tienda/', include ("tienda.urls")),
    path('carrito/', include ("carrito.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoExpo/belleluxe/carrito/urls.py
from django.urls import path

from . import views

app_name = 'carrito'
 
urlpatterns = [
    path('', views.corder, name="order"),
    path('add/',views.carrito_add, name ="carrito_add"),
    # path('detail/carrito/<int:pk>/', views.DetailCarrito, name='detail_carrito'),
    path('update/', views.UpdateCarrito, name='update_carrito'),
    path('delete/', views.DeleteCarrito, name='delete_carrito'),
    path('pago/', views.pagoos.as_view(), name='pagoC'),
    path('pedidos/', views.verPedidos.as_view(), name='pedidos'),


]

ProyectoExpo/belleluxe/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views


app_name="core"
urlpatterns=[
    path('', views.adm.as_view(), name="adm"),

    path('camping/', views.Campaign.as_view(), name="campaign"),
    path('detail/camping/<int:pk>/', views.DetailCampaign.as_view(), name='detail_campaign'),
    path('update/camping/<int:pk>/', views.UpdateCampaign.as_view(), name='update_campaign'),
    path('delete/camping/<int:pk>/', views.DeleteCampaign.as_view(), name='delete_campaign'),
    path('new/camping/', views.NewCampaign.as_view(), name='Newcampaign'),

    path('list/category/', views.list_category.as_view(), name="category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name='update_category'),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),
    path('new/category/', views.NewCategory.as_view(), name='Newcategory'),

    path('product/', views.product.as_view(), name="product"),
    path('recover/product/<int:pk>/', views.RecoverProduct.as_view(), name='recover_product'),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name='update_product'),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name='delete_product'),
    path('new/product/', views.NewProduct.as_view(), name='new_product'),

    path('list/customer/', views.list_customer.as_view(), name="customer"),
    path('detail/customer/<int:pk>/', views.DetailCustomer.as_view(), name='detail_customer'),
    path('update/customer/<int:pk>/', views.UpdateCustomer.as_view(), name='update_customer'),
    path('delete/customer/<int:pk>/', views.DeleteCustomer.as_view(), name='delete_customer'),

    path('list/ItemPedido', views.list_ItemPedido.as_view(), name="Itempedido"),
    path('recover/ItemPedido/<int:pk>/', views.RecoverItemPedido.as_view(), name='recover_itempedido'),
    path('update/ItemPedido/<int:pk>/', views.UpdateItemPedido.as_view(), name='update_itempedido'),
    path('delete/ItemPedido/<int:pk>/', views.DeteleItemPedido.as_view(), name='delete_itempedido'),  
   
    path('list/Pedido', views.list_pedidos.as_view(), name="pedido"),
    path('detail/Pedido/<int:pk>/', views.Detailpedidos.as_view(), name='detail_pedido'),
    path('update/Pedido/<int:pk>/', views.Updatepedidos.as_view(), name='update_pedido'),
    path('delete/Pedido/<int:pk>/', views.Deletepedidos.as_view(), name='delete_pedido'),   
    
]

ProyectoExpo/belleluxe/home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


app_name="home"
urlpatterns=[
    path('', views.inicio.as_view(), name="inicio"),
    path('nosotros/', views.nosotros.as_view(), name="nosotros"),
    path('blog/', views.blog.as_view(), name="blog"),
    path('servicios/', views.servicios.as_view(), name="servicios"),
    path('politicas/', views.politicas.as_view(), name="politicas"),
    path('perfil/<int:pk>/', views.perfil.as_view(), name="perfil"),

# Accesos
    path('registro/', views.registrar.as_view(), name='registro'),
    path('acceso/', views.Acceso.as_view(), name='acceso'),
    path('cierre/',views.cierre, name='cierre'),
    path('perfil/actualiar/<int:pk>/', views.UpdateProfile.as_view(), name="actualizarPerfil"),

]

ProyectoExpo/belleluxe/tienda/urls.py
from django.contrib import admin
from django.urls import path
from tienda import views


#  Compras 
app_name= "tienda"
urlpatterns=[
    path('', views.tienda.as_view(), name="tienda"),
    path('hombre/', views.hombre.as_view(), name="hombre"),
    path('mujer/', views.mujer.as_view(), name="mujer"),
    path('producto/<int:pk>/', views.producto.as_view(), name='producto'),
    path('categoria/<int:pk>/', views.Pcategoria.as_view(), name='Pcategoria'),
    path('busqueda/', views.busqueda.as_view(), name='busqueda'),
]

ProyectoExpo/belleluxe/tienda/models.py
from django.db import models

# Create your models here.

ProyectoExpo/belleluxe/tienda/views.py
from django.shortcuts import render
from django.views import generic
from core.models import Product, Category
# Create your views here.

# compras ---------------------------------------------------------


class tienda(generic.View):
    template_name="tienda/tienda.html"
    context={}
    def get(self, request, *args, **kwargs):
        category = Category.objects.all() 
        products = Product.objects.all()
        self.context = {
            "products": products,
            "category":category

        }
        return render(request, self.template_name, self.context)
    
# Lista de productos ---------------------------------------------------------

class hombre(generic.View):
    template_name="tienda/hombre.html"
    context={}
    def get(self, request, *args, **kwargs):
        products = Product.objects.filter(gender='Hombre')
        self.context = {
            "products": products
        }
        return render(request, self.template_name, self.context)
    
class mujer(generic.View):
    template_name="tienda/mujer.html"
    context={}
    def get(self, request, *args, **kwargs):
        products = Product.objects.filter(gender='Mujer')
        self.context = {
            "products": products
        }
        return render(request, self.template_name, self.context)

# Productos ---------------------------------------------------------

class producto(generic.DetailView):
    template_name="tienda/producto.html"
    context={}
    def get(self, request, pk, *args, **kwargs):
        product=Product.objects.get(pk=pk)
        # pase la consulta aqui para poder crear otra variable y en ella gurdar una lista de nuemros
        # no se porque el djago no permite numeros y afuersas te piden cosas que no sean numeros como lisras
        #                A                  B
        opciones = range(1, product.stock + 1)
        # esta funcion te devuelve una lista del A hasta UNO ANTES QUE B
        self.context = {
            "product": product,
            "opciones":opciones
        
        }
        return render(request, self.template_name,self.context)
    def post(self, request):
        pass

    
class Pcategoria(generic.View):
   template_name = "tienda/tienda.html"
   context={}
   def get(self, request, pk, *args, **kwargs):
        categorypk = Category.objects.get(pk=pk)
        category = Category.objects.all() 
        products = Product.objects.filter(category=categorypk)
        self.context = {
            "products": products,
            'category':category
        }
        return render(request, self.template_name, self.context)


   
class busqueda(generic.View):
   template_name = "tienda/tienda.html"
   context={}
   def get(self, request, *args, **kwargs):
        slug = 'vestido'
        products = Product.objects.filter(slug=slug)
        self.context = {
            
            "products": products
        }
        return render(request, self.template_name, self.context)

 

ProyectoExpo/belleluxe/templates/tienda/2tienda.html
{% extends "base/catalogo.html" %} 
{% block title %} Tienda {% endblock title %} 
{% block content %}
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Tienda</title>
  <!-- L I N K    TO    C S S   -->
  <link rel="stylesheet" href="css/style.css" />
  <!-- B O X   I C O N S    -->
  <link
    href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
    rel="stylesheet"
  />
</head>
<body>
  <!-- H E A D E R -->
  <header>
    <!--N A V -->
    <div class="nav container">
      <a href="#" class="logo">BELLE D' LUXE</a>
      <!--C A R T-I C O N -->
      <i class="bx bx-shopping-bag" id="cart-icon"></i>
      <!--C A R T-->
      <div class="cart">
        <h2 class="cart-title">Carrito</h2>
        <!--C O N T E N T -->
        <body>

          <ul>
            <li><a class="active" href="#home">Inicio</a></li>
            <li><a href="#news">News</a></li>
            <li><a href="#contact">Contact</a></li>
            <li><a href="#about">About</a></li>
          </ul>
          </body>
        <div class="cart-content">
          <div class="cart-box">
            <img src="imagenes/vestidorosa.jpeg" alt="" class="cart-img" />
            <div class="detail-box">
              <div class="cart-product-title">Vestidos</div>
              <div class="cart-price">$5000</div>
              <input type="number" value="1" class="cart-quantity" />
            </div>
            <!--R E M O V E   C A R T-->
            <i class="bx bxs-trash-alt cart-remove"></i>
          </div>
        </div>
        <!--T O T A L -->
        <div class="total">
          <div class="total-title">Total</div>
          <div class="total-price">$100</div>
        </div>
        <!--P A Y -->
        <button type="button" class="btn-buy">Pay now</button>
        <!--C A R T   C L O S E-->
        <i class="bx bx-x" id="close-cart"></i>
      </div>
    </div>
  </header>
  <!-- B A R R A  D E  N A V E G A C I O N -->

  <nav id="navegador" class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a href="{% url 'home:inicio' %}" class = navbar-brand> <img src="{% static 'imagenes/imagenestienda/mujertienda/conjunto1.jpg' %}" alt="" weight="80px" height="40px"></a>    
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>          

        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
                <li class="nav-item" ><a class="nav-link active" aria-current="page" href="{% url 'tienda:hombre' %}">TIENDA</a></li>
            </ul>                
        </div>
    </div>
  </nav>


  <!-- S H O P -->
  <section class="shop container">
    <h2 class="section-title">Shop Products</h2>
    <!--C O N T E N T -->
    <div class="shop-content">
      <!--  B O X 1 -->
      <div class="product-box">
        <img src="imagenes/vestidocarrusel1.jpeg" alt="" class="product-img" />
        <h2 class="product-title">VESTIDO ROSA</h2>
        <span class="price">$5000 mx</span>
        <i class="bx bx-shopping-bag add-cart"></i>
      </div>
      <!--  B O X 2 -->
      <div class="product-box">
        <img src="imagenes/vestidorosa.jpeg" alt="" class="product-img" />
        <h2 class="product-title">VESTIDO ROSA</h2>
        <span class="price">$5000 mx</span>
        <i class="bx bx-shopping-bag add-cart"></i>
      </div>
      <!--  B O X 3 -->
      <div class="product-box">
        <img src="imagenes/vestidorosa.jpeg" alt="" class="product-img" />
        <h2 class="product-title">VESTIDO ROSA</h2>
        <span class="price">$5000 mx</span>
        <i class="bx bx-shopping-bag add-cart"></i>
      </div>
      <!--  B O X 4 -->
      <div class="product-box">
        <img src="imagenes/vestidorosa.jpeg" alt="" class="product-img" />
        <h2 class="product-title">VESTIDO ROSA</h2>
        <span class="price">$5000 mx</span>
        <i class="bx bx-shopping-bag add-cart"></i>
      </div>
      <!--  B O X 5 -->
      <div class="product-box">
        <img src="imagenes/vestidorosa.jpeg" alt="" class="product-img" />
        <h2 class="product-title">VESTIDO ROSA</h2>
        <span class="price">$5000 mx</span>
        <i class="bx bx-shopping-bag add-cart"></i>
      </div>
      <!--  B O X 6 -->
      <div class="product-box">
        <img src="imagenes/vestidorosa.jpeg" alt="" class="product-img" />
        <h2 class="product-title">VESTIDO ROSA</h2>
        <span class="price">$5000 mx</span>
        <i class="bx bx-shopping-bag add-cart"></i>
      </div>
      <!--  B O X 7 -->
      <div class="product-box">
        <img src="imagenes/vestidorosa.jpeg" alt="" class="product-img" />
        <h2 class="product-title">VESTIDO ROSA</h2>
        <span class="price">$5000 mx</span>
        <i class="bx bx-shopping-bag add-cart"></i>
      </div>
      <!--  B O X 8 -->
      <div class="product-box">
        <img src="imagenes/vestidorosa.jpeg" alt="" class="product-img" />
        <h2 class="product-title">VESTIDO ROSA</h2>
        <span class="price">$5000 mx</span>
        <i class="bx bx-shopping-bag add-cart"></i>
      </div>
    </div>
  </section>
  <!-- L I N K to J S -->
  <script src="javascript/main.js"></script>
</body>
{% endblock content %}

ProyectoExpo/belleluxe/templates/tienda/hombre.html
{% extends 'base/catalogo.html' %}

{% block title %} Hombre | BELLE D' LUXE {% endblock title %}

ProyectoExpo/belleluxe/templates/tienda/mujer.html
{% extends 'base/base.html' %}
{% block title %}Mujer | BELLE D' LUXE{% endblock title %}
{% load static %}

{% block content %}
                <!--! form para el catalogo -->
<div class="row row-cols-1 row-cols-md-3 g-4"> 
{% for product in products %}
    <div class="col">
      <div class="card h-100">
        <img src="{{ product.imagen1.url }}" alt="{{ product.name }}" class="img-fluid">
        <div class="card-body">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text">{{ product.description }}</p>
          <a href="{% url 'tienda:producto' product.id %}" class="btn btn-outline-info"> Ver </a>
        </div>
      </div>
    </div>
{% endfor %}
</div>


{% endblock content %}

ProyectoExpo/belleluxe/templates/tienda/producto.html
{% extends 'base/principal.html' %}
{% load static %}

{% block title %}
{{ product.name }}
{% endblock title %}

{% block content %}

<style>

     #btn1{

      background-color: #000000;
      border: 1px solid rgb(255, 255, 255);
       color: rgb(255, 255, 255);
       padding: 10px 60px;
       text-align: center;
       text-decoration: none;
       display: inline-block;
       font-size: 16px;
       margin-left: 5%;
       margin-top: 4%;
       cursor: pointer;
       border-radius: 30px;

     }

</style>


<br>
<br>
  <div class="container">
    <div class="row">
      <div class="col-md-6">

        <p id="nameproduct" style="font-size: 250%; padding-top: 20%; padding-bottom: 20%;">{{ product.name }}</p>
        <ul class="list-group">
          <li class="list-group-item"><strong>Descripción:</strong> {{ product.description }}</li>
          <li class="list-group-item"><strong>Talla:</strong> {{ product.size }}</li>
          <li class="list-group-item"><strong>Precio (Unidad):</strong> $ {{ product.price }}</li>
          <li class="list-group-item"><strong>Stock:</strong> {{ product.stock }}</li>

          <div class="col-md-6">
            <br>
            <label for="select">Cantidad</label>
            <select id="select" name="cantidad">
                {% for opcion in opciones %}
                    <option value="{{ opcion }}">{{ opcion }}</option>
                {% endfor %}
            </select>
        </div>
        


          <div class="col-6 text-end">

<br>

  <button type="button" id="add-button" value="{{product.id}}" class="btn btn-dark">Añadir al carrito</button> 




        </ul>
      </div>
      
      <div class="col-md-6">
        <img src="{{ product.imagen1.url }}" alt="{{ product.name }}" class="img-fluid">
      </div>
    </div>
  </div>
  <a id="btn1" href="{% url 'tienda:tienda'%}" class="btn btn-info" role="button">Regresar</a>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "carrito:carrito_add" %}',
            data: {
                productId: $('#add-button').val(),
                productQty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("carrito-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>


{% endblock content %}

ProyectoExpo/belleluxe/templates/tienda/tienda.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Tienda{% endblock title %}
{% block content %}


   <!-- L I N K    TO    C S S   --> 
   <link rel="stylesheet" href="{% static 'itcss/styletienda.css' %}">
   <!-- B O X   I C O N S    -->
   <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- H E A D E R -->
    <style>
      .product-box a {
          text-decoration: none; /* Quitar subrayado */
          color: black; /* Color del texto en negro */
      }
  </style>
    <!-- S H O P --> 
    <section class="shop container">
       <!--Barra de navegacion -->        
        <!--C O N T E N T -->
        <div class="shop-content">
            <!--  B O X -->
            {% for product in products %}
            <div class="product-box">
              <a href="{% url 'tienda:producto' product.id %}" class="product-link" >
                <img src="{{ product.imagen1.url }}" alt="{{ product.name }}" class="product-img">
                <h2 class="product-title">{{ product.name }} </h2>
                <span class="price">{{ product.price }}$</span>
                
                  <i class='bx bx-shopping-bag add-cart'></i>
                </a>
                
            </div>
            {% endfor %}
        </div>
       </section>
    <!-- L I N K to J S -->
    <script src="{%static 'javascript/main.js' %}"></script>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>

{% endblock content %}