ProyectoExpo/belleluxe/belleluxe/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('adm/', include("core.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tienda/', include ("tienda.urls")),
    path('carrito/', include ("carrito.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoExpo/belleluxe/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views


app_name="core"
urlpatterns=[
    path('', views.adm.as_view(), name="adm"),

    path('camping/', views.Campaign.as_view(), name="campaign"),
    path('detail/camping/<int:pk>/', views.DetailCampaign.as_view(), name='detail_campaign'),
    path('update/camping/<int:pk>/', views.UpdateCampaign.as_view(), name='update_campaign'),
    path('delete/camping/<int:pk>/', views.DeleteCampaign.as_view(), name='delete_campaign'),
    path('new/camping/', views.NewCampaign.as_view(), name='Newcampaign'),

    path('list/category/', views.list_category.as_view(), name="category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name='update_category'),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),
    path('new/category/', views.NewCategory.as_view(), name='Newcategory'),

    path('product/', views.product.as_view(), name="product"),
    path('recover/product/<int:pk>/', views.RecoverProduct.as_view(), name='recover_product'),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name='update_product'),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name='delete_product'),
    path('new/product/', views.NewProduct.as_view(), name='new_product'),

    path('list/customer/', views.list_customer.as_view(), name="customer"),
    path('detail/customer/<int:pk>/', views.DetailCustomer.as_view(), name='detail_customer'),
    path('update/customer/<int:pk>/', views.UpdateCustomer.as_view(), name='update_customer'),
    path('delete/customer/<int:pk>/', views.DeleteCustomer.as_view(), name='delete_customer'),

    path('list/ItemPedido', views.list_ItemPedido.as_view(), name="Itempedido"),
    path('recover/ItemPedido/<int:pk>/', views.RecoverItemPedido.as_view(), name='recover_itempedido'),
    path('update/ItemPedido/<int:pk>/', views.UpdateItemPedido.as_view(), name='update_itempedido'),
    path('delete/ItemPedido/<int:pk>/', views.DeteleItemPedido.as_view(), name='delete_itempedido'),  
   
    path('list/Pedido', views.list_pedidos.as_view(), name="pedido"),
    path('detail/Pedido/<int:pk>/', views.Detailpedidos.as_view(), name='detail_pedido'),
    path('update/Pedido/<int:pk>/', views.Updatepedidos.as_view(), name='update_pedido'),
    path('delete/Pedido/<int:pk>/', views.Deletepedidos.as_view(), name='delete_pedido'),   
    
]

ProyectoExpo/belleluxe/core/models.py
from audioop import reverse
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

TipoGenero=(("Hombre","Hombre"),("Mujer","Mujer"))

class campaign(models.Model):
    lasteditor = models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=30, default='generico')
    year=models.DateField(auto_now_add=True)
    def __str__(self):
        return self.name



class Category(models.Model):
    lasteditor = models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=25, default='generic category')
    
    class Meta:
        verbose_name_plural = 'categories'
    def get_absolute_url(self):
        return reverse('core:category', args=[str(self.name)])
    def __str__(self):
        return self.name



class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name_first=models.CharField(max_length=35)
    last_name_pat=models.CharField(max_length=25)
    last_name_mat=models.CharField(max_length=25, blank=True, null=True)
    phone=models.CharField(max_length=15)
    cp=models.CharField(max_length=5)
    streat=models.CharField(max_length=25)
    number_home=models.CharField(max_length=5)
    def __str__(self):
        return self.name_first


        

#Agregar un max_length al stock
class Product(models.Model):
    lasteditor = models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=35)   
    campaign=models.ForeignKey(campaign, on_delete=models.CASCADE)
    gender=models.CharField(max_length=10, choices=TipoGenero)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    description=models.CharField(max_length=256)
    size=models.CharField(max_length=4)
    price=models.FloatField(default=0.0)
    status=models.BooleanField(default=False)
    stock=models.IntegerField(max_length=3,default=0)
    slug=models.SlugField(max_length=36)
    imagen1 = models.ImageField(upload_to='media/', null=True) 

    
    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-status',)

    def get_absolute_url(self):
        return reverse('core:product', args=[self.slug])
    
    def __str__(self):
        return self.name
#Hacer CRUD
class ItemPedido(models.Model):
    pedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    codigo_producto = models.CharField(max_length=20, unique=True) 

#hacer CRUD
class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Product, through=ItemPedido)
    fecha = models.DateTimeField(auto_now_add=True)
    codigo_pedido = models.CharField(max_length=20, unique=True)

ProyectoExpo/belleluxe/core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import *
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator


# Esta cosa devuelve un buliano sobre si es staff o no
def bloqueador(user):
    return user.is_staff

#Ese decorador verificar el buliano
#El dispatch se encarga de asegurar que sea el decorador lo primero en la vissta 
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class adm(generic.View):
    tamplate_name="core/admin.html"
    context={}
    def get(self, request, *args, **kwargs):
        return render(request, self.tamplate_name, self.context)


#Campaign--------------------------------------------------------------------------
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class Campaign(generic.View):
   template_name="core/campaign/campaign.html"
   context={}
   def get(self,request):
       self.context= {
           "campaign": campaign.objects.all()
       }
       return render(request, self.template_name, self.context)


@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')  
class DetailCampaign(generic.DetailView):
   template_name = "core/campaign/detail_campaign.html"
   model = campaign

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class NewCampaign(generic.CreateView):
   template_name="core/campaign/NewCampaign.html"
   model = campaign
   form_class = NewCampaignform
   success_url = reverse_lazy("core:campaign")

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class UpdateCampaign(generic.UpdateView):
   template_name="core/campaign/update_campaign.html"
   model = campaign
   form_class = UpdateCampaignForm
   success_url = reverse_lazy("core:campaign")


@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class DeleteCampaign(generic.DeleteView):
   template_name="core/campaign/delete_campaign.html"
   model = campaign
   success_url = reverse_lazy("core:campaign")


#Category--------------------------------------------------------------------------
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class list_category(generic.View):
   template_name="core/category/category.html"
   context={}
   def get(self,request):
      categories = Category.objects.all()
      self.context = {
         "category": categories
      }
      return render(request, self.template_name, self.context)

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class NewCategory(generic.CreateView):
   template_name="core/category/New_category.html"
   model = Category
   form_class = NewCategoryForm
   success_url = reverse_lazy("core:category")

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class DetailCategory(generic.DetailView):
   template_name = "core/category/detail_category.html"
   model = Category
   def get(self, request, pk, *args, **kwargs):
      categories = Category.objects.get(pk=pk)
      self.context = {
         "category": categories
      }
      return render(request, self.template_name,self.context)
   
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class UpdateCategory(generic.UpdateView):
   template_name="core/category/update_category.html"
   model = Category
   form_class = UpdateCategoryForm
   success_url = reverse_lazy("core:category")

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class DeleteCategory(generic.DeleteView):
   template_name="core/category/delete_category.html"
   model = Category
   success_url = reverse_lazy("core:category")

#Product--------------------------------------------------------------------------
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class product(generic.View):
   template_name = "core/product/product.html"
   context = {}
   def get(self, request, *args, **kwargs):
      products = Product.objects.all()
      self.context = {
         "products": products
      }
      return render(request, self.template_name, self.context)
   
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class NewProduct(generic.CreateView):
   template_name = "core/product/new_product.html"
   model = Product
   form_class = NewProductForm
   success_url = reverse_lazy("core:product")

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class RecoverProduct(generic.View):
   template_name = "core/product/recover_product.html"
   context = {}

   def get(self, request, pk, *args, **kwargs):
      self.context = {
         "product": Product.objects.get(pk=pk)
      }
      return render(request, self.template_name,self.context)

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class UpdateProduct(generic.UpdateView):
   template_name = "core/product/update_product.html"
   model = Product
   form_class = UpdateProductForm
   success_url = reverse_lazy("core:product")

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class DeleteProduct(generic.DeleteView):
   template_name = "core/product/delete_product.html"
   model = Product
   success_url = reverse_lazy("core:product")


#Customer-----------------------------------------------------------------------
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class list_customer(generic.View):
   template_name="core/customer/customer.html"
   context={}
   def get(self,request):
       self.context= {
           "customer": Customer.objects.all()
       }
       return render(request, self.template_name, self.context)
   
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class DetailCustomer(generic.DetailView):
   template_name = "core/customer/detail_customer.html"
   model = Customer

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class UpdateCustomer(generic.UpdateView):
   template_name="core/customer/update_customer.html"
   model = Customer
   form_class = UpdateCustomerForm
   success_url = reverse_lazy("core:customer")

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class DeleteCustomer(generic.DeleteView):
   template_name="core/customer/delete_customer.html"
   model = Customer
   success_url = reverse_lazy("core:customer")

#ItemPedido-----------------------------------------------------------------------

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class list_ItemPedido(generic.View):
   template_name = "core/itempedido/Itempedido.html"
   context = {}
   def get(self, request, *args, **kwargs):
      ItemPedidos = ItemPedido.objects.all()
      self.context = {
         "ItemPedido": ItemPedidos
      }
      return render (request, self.template_name, self.context)
   
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class RecoverItemPedido(generic.View):
   template_name = "core/itempedido/recover_itempedido.html"
   context = {}
   def get(self, request, pk, *args, **kwargs):
      self.context = {
         "ItemPedido" : ItemPedido.objects.get(pk=pk)
      }
      return render(request, self.template_name, self.context)

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class UpdateItemPedido(generic.UpdateView):
   template_name = "core/itempedido/update_itempedido.html"
   model = ItemPedido
   form_class = UpdateItemPedidoForm
   success_url = reverse_lazy ("core:Itempedido")

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class DeteleItemPedido(generic.DeleteView):
   template_name = "core/itempedido/delete_itempedido.html"
   model = ItemPedido
   success_url = reverse_lazy ("core:Itempedido")

   

#Pedido-----------------------------------------------------------------------

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class list_pedidos(generic.View):
   template_name="core/pedido/pedido.html"
   context={}
   def get(self,request):
      Pedidos = Pedido.objects.all()
      self.context= {
        "pedidos": Pedidos
      }
      return render(request, self.template_name, self.context)
   


   
@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class Detailpedidos(generic.View):
   template_name = "core/pedido/detail_pedido.html"
   context={}
   def get(self, request, pk, *args, **kwargs):
      ped = Pedido.objects.get(pk=pk)
      self.context = {
         "ped" : ped
      }
      return render(request, self.template_name, self.context)
   




@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class Updatepedidos(generic.UpdateView):
   template_name="core/pedido/update_pedido.html"
   model = Pedido
   form_class = UpdatepedidosForm
   success_url = reverse_lazy("core:pedido")

@method_decorator(user_passes_test(bloqueador, login_url='/'), name='dispatch')
class Deletepedidos(generic.DeleteView):
   template_name="core/pedido/delete_pedido.html"
   model = Pedido
   success_url = reverse_lazy("core:pedido")

ProyectoExpo/belleluxe/templates/core/product/delete_product.html
{% extends 'base/admin.html' %}

{% block title %}
Borrar {{ object.name }}
{% endblock title %}

{% block content %}
<br>
<br>
    <form action="" method="post">
        {% csrf_token %}
            <h4>Borrar Producto</h4>
            <p>¿Realmente deseas borrar este producto : {{ object.name }} ? </p>
            <button type="submit" class="btn btn-danger">Borrar Producto</button>
            <a href="{% url 'core:product' %}" class="btn btn-warning">Cancelar</a>
    </form>
{% endblock content %}  

ProyectoExpo/belleluxe/templates/core/product/new_product.html
{% extends 'base/admin.html' %}

{% block title %}
Nuevo producto
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success form-control">Crear producto</button>
        <br>
        <a href="{% url 'core:product' %}" class="btn btn-outline-warning form-control">Cancelar</a>
    </form>
{% endblock content %}

ProyectoExpo/belleluxe/templates/core/product/product.html
{% extends 'base/admin.html' %}

{% block title %}
PRODUCT VIEW
{% endblock title %}

{% block content %}
<br> 
<center><h2>Productos</h2></center>
<br> 
<hr>
    <a href="{% url 'core:new_product' %}" class="btn btn-outline-success form-control">Crear nuevo producto</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>Nombre del producto</th>
            <th>Campaña</th>
            <th>Descripción</th>
            <th>Status</th>
            <th>Cantidad</th>
            <th></th>
            <th>Acciones</th>
            <th></th>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.campaign }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.status }}</td>
                    <td>{{ product.stock }}</td>                    
                    <td><a href="{% url 'core:recover_product' product.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:update_product' product.id %}" class="btn btn-outline-warning"> Actualizar </a></td>
                    <td><a href="{% url 'core:delete_product' product.id %}" class="btn btn-outline-danger"> Borrar </a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>    

{% endblock content %}

ProyectoExpo/belleluxe/templates/core/product/recover_product.html
{% extends 'base/admin.html' %}

{% block title %}
{{ product.name }}
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Detalles del producto</h2>
        <ul class="list-group">
          <li class="list-group-item"><strong>Id:</strong> {{ product.id }}</li>
          <li class="list-group-item"><strong>Nombre:</strong> {{ product.name }}</li>
          <li class="list-group-item"><strong>Decripción:</strong> {{ product.description }}</li>
          <li class="list-group-item"><strong>Campaña:</strong> {{ product.campaign }}</li>
          <li class="list-group-item"><strong>Genero:</strong> {{ product.gender }}</li>
          <li class="list-group-item"><strong>Categoría:</strong> {{ product.category }}</li>
          <li class="list-group-item"><strong>Talla:</strong> {{ product.size }}</li>
          <li class="list-group-item"><strong>Precio (Unidad):</strong> {{ product.price }}</li>
          <li class="list-group-item"><strong>Estatus:</strong> {{ product.status }}</li>
          <li class="list-group-item"><strong>Stock:</strong> {{ product.stock }}</li>
        </ul>
      </div>
        <div class="col-md-6">
          <img src="{{ product.imagen1.url }}" alt="{{ product.name }}" class="img-fluid">
        </div>
        
      </div>
  
        <br>

    <a href="{% url 'core:product' %}" class="btn btn-link">Volver</a>   
  </div>
{% endblock content %}

ProyectoExpo/belleluxe/templates/core/product/update_product.html
{% extends 'base/admin.html' %}

{% block title %}
Actualizar Producto
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary form-control">Actualizar producto</button>
        <br>
        <a href="{% url 'core:product' %}" class="btn btn-outline-warning form-control">Cancelar</a>
    </form>
{% endblock content %}